# SPDX-FileCopyrightText: © Vegard IT GmbH (https://vegardit.com)
# SPDX-License-Identifier: Apache-2.0
#
# Author: Sebastian Thomschke, Vegard IT GmbH
#
# https://github.com/vegardit/vegardit-maven-parent
#
# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
name: Build

on:
  push:
    branches:
    - '**'
    tags-ignore:
    - '**'
    paths-ignore:
    - '**/*.adoc'
    - '**/*.md'
    - '.github/*.yml'
  pull_request:
  workflow_dispatch:
    # https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
    inputs:
      additional_maven_args:
        description: 'Additional Maven Args'
        required: false
        default: ''

env:
  JAVA_VERSION: 11

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v3 #https://github.com/actions/checkout

    - name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v3 #https://github.com/actions/setup-java
      with:
        distribution: 'zulu'
        java-version: ${{ env.JAVA_VERSION }}

    # reusing CDS archives of the same JVM randomly fails in GitHub Actions with
    # "An error has occurred while processing the shared archive file. shared class paths mismatch"
    #- name: Calculate Java version checksum
    #  id: java-version-checksum
    #  run: |
    #    echo "::set-output name=md5sum::$(java -version 2>&1 | md5sum | cut -f1 -d" ")"
    #- name: Cache Java CDS archive
    #  uses: actions/cache@v3
    #  with:
    #    path: |
    #      ~/.xshare/${{ steps.java-version-checksum.outputs.md5sum }}
    #    key: ${{ runner.os }}-xshare-${{ steps.java-version-checksum.outputs.md5sum }}

    - name: "Cache: Local Maven Repository"
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
          !~/.m2/repository/com/vegardit/maven
        key: ${{ runner.os }}-mvnrepo-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-mvnrepo-

    - name: "Cache: Maven Binaries"
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/bin
        key: ${{ runner.os }}-mvnbin-${{ hashFiles('.ci/build.sh') }}

    - name: Test with Maven
      id: maven-test
      if: ${{ github.ref != 'refs/heads/main' }}
      env:
        GITHUB_USER: ${{ github.actor }}
        GITHUB_API_KEY: ${{ github.token }}
        MAY_CREATE_RELEASE: false
      run: |
        bash .ci/build.sh ${{ github.event.inputs.additional_maven_args }}

    - name: Build with Maven
      id: maven-build
      if: github.ref == 'refs/heads/main'
      env:
        DEPLOY_SNAPSHOTS_TO_GITHUB_BRANCH: true
        GITHUB_USER: ${{ github.actor }}
        GITHUB_API_KEY: ${{ secrets.GH_API_TOKEN }}
        MAY_CREATE_RELEASE: true
        SIGN_KEY: ${{ secrets.GPG_SIGN_KEY }}
        SIGN_KEY_PASS: ${{ secrets.GPG_SIGN_KEY_PWD }}
        SONATYPE_OSSRH_USER: ${{ secrets.SONATYPE_OSSRH_USER }}
        SONATYPE_OSSRH_USER_TOKEN: ${{ secrets.SONATYPE_OSSRH_USER_TOKEN }}
      run: |
        set -eu

        # https://github.community/t/github-actions-bot-email-address/17204
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        bash .ci/build.sh ${{ github.event.inputs.additional_maven_args }}
